dist: xenial

language: java

services:
  - docker


addons:
  apt:
    sources:
      - sourceline: "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8"
        key_url: "https://bazel.build/bazel-release.pub.gpg"
    packages:
      - wget
      - pkg-config
      - zip
      - g++
      - zlib1g-dev
      - unzip
      - python
      - openjdk-8-jdk
      - bazel


before_script:
  - bazel version
  - docker version

script:
  - bazel test //test:test
  - bazel build //main:main_deploy.jar
  - bazel run //docker:image
  - docker run -it --rm bazel/docker:image

