package(default_visibility = ["//visibility:public"])

java_binary(
    name = "main",
    main_class = "com.example.Runner",
    srcs = glob(["src/java/com/example/*.java"]),
    deps = [
        "//lib:greeter"
    ],
)
